# Generated by Django 5.0.14 on 2026-09-28 19:44

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id_dispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('dev_eui', models.CharField(help_text='Identificador LoRaWAN grabado de fábrica (16 dígitos hex)', max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Fa-f]{16}$', 'Debe tener exactamente 16 dígitos hexadecimales.')])),
                ('nombre', models.CharField(help_text='Etiqueta legible, p. ej. Nodo 07', max_length=80)),
                ('activo', models.BooleanField(default=True, help_text='Un nodo inhabilitado se ignora en el panel sin borrar su historial')),
                ('ultima_bateria_mv', models.IntegerField(blank=True, null=True)),
                ('ultimo_contacto', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dispositivo',
            },
        ),
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id_gateway', models.AutoField(primary_key=True, serialize=False)),
                ('gateway_eui', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[0-9A-Fa-f]{16}$', 'Debe tener exactamente 16 dígitos hexadecimales.')])),
                ('nombre', models.CharField(help_text='Típicamente el sitio de instalación', max_length=80)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'db_table': 'gateway',
            },
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
                ('id_visitante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('contacto_emergencia', models.CharField(help_text='Nombre y teléfono de la persona a notificar', max_length=120)),
                ('notas_medicas', models.TextField(blank=True, help_text='Alergias, padecimientos u otras condiciones relevantes para el rescate')),
            ],
            options={
                'db_table': 'visitante',
            },
        ),
        migrations.CreateModel(
            name='ZonaGeografica',
            fields=[
                ('id_zona', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='P. ej. Sendero Norte', max_length=80)),
                ('tipo', models.CharField(choices=[('SENDERO', 'Sendero'), ('MIRADOR', 'Mirador'), ('ZONA_RIESGO', 'Zona de riesgo'), ('AREA_COMUN', 'Área común')], max_length=20)),
                ('area', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name': 'zona geográfica',
                'verbose_name_plural': 'zonas geográficas',
                'db_table': 'zona_geografica',
            },
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='geolocalizacion.dispositivo')),
                ('visitante', models.ForeignKey(db_column='id_visitante', on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='geolocalizacion.visitante')),
            ],
            options={
                'verbose_name': 'asignación',
                'verbose_name_plural': 'asignaciones',
                'db_table': 'asignacion_dis_vis',
            },
        ),
        migrations.CreateModel(
            name='Vigilante',
            fields=[
                ('id_vigilante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vigilante', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vigilante',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id_incidente', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EN_ATENCION', 'En atención'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado por el visitante'), ('FALSA_ALARMA', 'Falsa alarma')], default='ACTIVO', max_length=14)),
                ('ultima_posicion', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('abierto_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('notas_rescate', models.TextField(blank=True)),
                ('asignacion', models.ForeignKey(blank=True, db_column='id_asignacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='geolocalizacion.asignacion')),
                ('dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.PROTECT, related_name='incidentes', to='geolocalizacion.dispositivo')),
                ('vigilante', models.ForeignKey(blank=True, db_column='id_vigilante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_cerrados', to='geolocalizacion.vigilante')),
                ('zona', models.ForeignKey(blank=True, db_column='id_zona', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='geolocalizacion.zonageografica')),
            ],
            options={
                'db_table': 'incidente',
                'ordering': ['-abierto_en'],
            },
        ),
        migrations.CreateModel(
            name='RegistroGPS',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('punto', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('es_sos', models.BooleanField(default=False)),
                ('bateria_mv', models.IntegerField(blank=True, null=True)),
                ('rssi', models.SmallIntegerField(blank=True, help_text='dBm', null=True)),
                ('snr', models.FloatField(blank=True, help_text='dB', null=True)),
                ('fcnt', models.IntegerField()),
                ('recibido_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispositivo', models.ForeignKey(db_column='id_dispositivo', on_delete=django.db.models.deletion.PROTECT, related_name='registros', to='geolocalizacion.dispositivo')),
                ('gateway', models.ForeignKey(blank=True, db_column='id_gateway', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros', to='geolocalizacion.gateway')),
                ('incidente', models.ForeignKey(blank=True, db_column='id_incidente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='geolocalizacion.incidente')),
            ],
            options={
                'verbose_name': 'registro GPS',
                'verbose_name_plural': 'registros GPS',
                'db_table': 'registro_gps',
                'ordering': ['-recibido_en'],
                'indexes': [models.Index(fields=['dispositivo', '-recibido_en'], name='registro_gp_id_disp_34cddf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='asignacion',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_devolucion__isnull', True)), fields=('dispositivo',), name='asignacion_vigente_unica', violation_error_message='Este nodo ya tiene un préstamo vigente.'),
        ),
    ]
